/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cuid = string;

export interface Faq {
  faqs: Faq1[];
}
export interface Faq1 {
  id: Cuid;
  question: string;
  answer: string;
}
