/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cuid = string;

export interface Product {
  id: Cuid;
  metaDescription?: string;
  metaKeywords?: string;
  title: string;
  price?: number;
  description: string;
  body: string;
  facturer?: string;
  categories?: string[];
  thumbnail: string;
  images: string[];
  videos?: Video[];
}
export interface Video {
  type: "youtube" | "tiktok" | "rutube";
  url: string;
}
